#========================================================================
# Spack Packages Labels
#========================================================================
#------------------------------------------------------------------------
# CI/CD Modifications
#------------------------------------------------------------------------
ci:
  filename: '^\.(ci|github).*\.ya?ml$'

#------------------------------------------------------------------------
# Test Modifications
#------------------------------------------------------------------------
tests:
  filename: '^tests/.*$'

#------------------------------------------------------------------------
# Build Systems
#------------------------------------------------------------------------
build-systems:
  filename: '^repos/spack_repo/builtin/build_systems/.*$'

#------------------------------------------------------------------------
# Package Types
#------------------------------------------------------------------------
intel:
  package: 'intel'

python:
  package:
    - '^python$'
    - '^py_'

R:
  package:
    - '^r$'
    - '^r_'

#------------------------------------------------------------------------
# Package Statuses
#------------------------------------------------------------------------
new-package:
  filename: '^repos/spack_repo/builtin/packages/[^/]+/package.py$'
  status: 'added'

update-package:
  filename: '^repos/spack_repo/builtin/packages/[^/]+/package.py$'
  status:
    - 'modified'
    - 'renamed'

remove-package:
  filename: '^repos/spack_repo/builtin/packages/[^/]+/package.py$'
  status:
    - 'removed'

#------------------------------------------------------------------------
# Package Properties
#------------------------------------------------------------------------
maintainers:
  patch: '[+-] +maintainers\('

licenses:
  patch: '[+-] +license\('

new-version:
  patch: '\+ +version\('

new-variant:
  patch: '\+ +variant\('

conflicts:
  patch: '[+-] +conflicts\('

dependencies:
  patch: '[+-] +depends_on\('

extends:
  patch: '[+-] +extends\('

virtual-dependencies:
  patch: '[+-] +provides\('

patch:
  patch: '[+-] +patch\('

resources:
  patch: '[+-] +resource\('

external-packages:
  patch: '[+-] +def determine_spec_details\('

libraries:
  patch: '[+-] +def libs\('

headers:
  patch: '[+-] +def headers\('

stand-alone-tests:
  patch: '[+-] +def test[_]?.*\('
