# Copyright Spack Project Developers. See COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

import collections
import errno
import os
import shutil
import stat
import sys
from pathlib import Path
from typing import Tuple

import pytest

import spack.bootstrap.core
import spack.caches
import spack.package_base
import spack.solver.asp
import spack.stage
import spack.subprocess_context
from spack.concretize import concretize_one
from spack.config import (
    CONFIG_DEFAULTS,
    DirectoryConfigScope,
    InternalConfigScope,
    use_configuration,
)
from spack.enums import ConfigScopePriority
from spack.installer import PackageInstaller
from spack.package import copy_tree, host_platform, mkdirp, remove_linked_tree
from spack.platforms import Test as TestPlatform
from spack.platforms import use_platform
from spack.repo import from_path, use_repositories
from spack.store import use_store
from spack.vendor.archspec.cpu import host as host_cpu


@pytest.fixture(autouse=True)
def check_config_fixture(request):
    if "config" in request.fixturenames and "mutable_config" in request.fixturenames:
        raise RuntimeError("'config' and 'mutable_config' are both requested")


def ensure_configuration_fixture_run_before(request):
    """Ensure that fixture mutating the configuration run before the one where
    the function is called.
    """
    if "config" in request.fixturenames:
        request.getfixturevalue("config")
    if "mutable_config" in request.fixturenames:
        request.getfixturevalue("mutable_config")


@pytest.fixture(autouse=True)
def clear_recorded_monkeypatches():
    yield
    spack.subprocess_context.MONKEYPATCHES.clear()


@pytest.fixture(scope="session", autouse=True)
def record_monkeypatch_setattr():
    import _pytest

    saved_setattr = _pytest.monkeypatch.MonkeyPatch.setattr

    def record_setattr(cls, target, name, value, *args, **kwargs):
        spack.subprocess_context.MONKEYPATCHES.append((target, name))
        saved_setattr(cls, target, name, value, *args, **kwargs)

    _pytest.monkeypatch.MonkeyPatch.setattr = record_setattr
    try:
        yield
    finally:
        _pytest.monkeypatch.MonkeyPatch.setattr = saved_setattr


#
# These fixtures are applied to all tests
#
@pytest.fixture(scope="function", autouse=True)
def no_chdir():
    """Ensure that no test changes Spack's working dirctory.

    This prevents Spack tests (and therefore Spack commands) from
    changing the working directory and causing other tests to fail
    mysteriously. Tests should use ``working_dir`` or ``py.path``'s
    ``.as_cwd()`` instead of ``os.chdir`` to avoid failing this check.

    We assert that the working directory hasn't changed, unless the
    original wd somehow ceased to exist.

    """
    original_wd = os.getcwd()
    yield
    if os.path.isdir(original_wd):
        assert os.getcwd() == original_wd


def onerror(func, path, error_info):
    # Python on Windows is unable to remvove paths without
    # write (IWUSR) permissions (such as those generated by Git on Windows)
    # This method changes file permissions to allow removal by Python
    os.chmod(path, stat.S_IWUSR)
    func(path)


@pytest.fixture(scope="function", autouse=True)
def mock_stage(tmp_path_factory: pytest.TempPathFactory, monkeypatch, request):
    """Establish the temporary build_stage for the mock archive."""
    # The approach with this autouse fixture is to set the stage root
    # instead of using spack.config.override() to avoid configuration
    # conflicts with dozens of tests that rely on other configuration
    # fixtures, such as config.

    if "nomockstage" in request.keywords:
        # Tests can opt-out with @pytest.mark.nomockstage
        yield None
        return

    # Set the build stage to the requested path
    new_stage = tmp_path_factory.mktemp("mock-stage")

    # Ensure the source directory exists within the new stage path
    source_path = new_stage / spack.stage._source_path_subdir
    source_path.mkdir(parents=True, exist_ok=True)

    monkeypatch.setattr(spack.stage, "_stage_root", str(new_stage))

    yield str(new_stage)

    # Clean up the test stage directory
    if new_stage.is_dir():
        shutil.rmtree(new_stage, onerror=onerror)


@pytest.fixture(scope="session")
def ignore_stage_files():
    """Session-scoped helper for check_for_leftover_stage_files.

    Used to track which leftover files in the stage have been seen.
    """
    # to start with, ignore the .lock file at the stage root.
    return set([".lock", spack.stage._source_path_subdir, "build_cache"])


def remove_whatever_it_is(path):
    """Type-agnostic remove."""
    if os.path.isfile(path):
        os.remove(path)
    elif os.path.islink(path):
        remove_linked_tree(path)
    else:
        shutil.rmtree(path, onerror=onerror)


@pytest.fixture
def working_env():
    saved_env = os.environ.copy()
    yield
    # os.environ = saved_env doesn't work
    # it causes module_parsing::test_module_function to fail
    # when it's run after any test using this fixutre
    os.environ.clear()
    os.environ.update(saved_env)


@pytest.fixture(scope="function", autouse=True)
def check_for_leftover_stage_files(request, mock_stage, ignore_stage_files):
    """
    Ensure that each (mock_stage) test leaves a clean stage when done.

    Tests that are expected to dirty the stage can disable the check by
    adding::

        @pytest.mark.disable_clean_stage_check

    and the associated stage files will be removed.
    """
    stage_path = mock_stage

    yield

    files_in_stage = set()
    try:
        stage_files = os.listdir(stage_path)
        files_in_stage = set(stage_files) - ignore_stage_files
    except OSError as err:
        if err.errno == errno.ENOENT or err.errno == errno.EINVAL:
            pass
        else:
            raise

    if "disable_clean_stage_check" in request.keywords:
        # clean up after tests that are expected to be dirty
        for f in files_in_stage:
            path = os.path.join(stage_path, f)
            remove_whatever_it_is(path)
    else:
        ignore_stage_files |= files_in_stage
        assert not files_in_stage


class MockCache:
    def store(self, copy_cmd, relative_dest):
        pass

    def fetcher(self, target_path, digest, **kwargs):
        return MockCacheFetcher()


class MockCacheFetcher:
    def fetch(self):
        raise Exception("Mock cache always fails for tests")

    def __str__(self):
        return "[mock fetch cache]"


@pytest.fixture(autouse=True)
def mock_fetch_cache(monkeypatch):
    """Substitutes FETCH_CACHE that raises on fetch."""
    monkeypatch.setattr(spack.caches, "FETCH_CACHE", MockCache())


@pytest.fixture(autouse=True, scope="session")
def _use_test_platform():
    # This is the only context manager used at session scope (see note
    # below for more insight) since we want to use the test platform as
    # a default during tests.
    with use_platform(TestPlatform()):
        yield


#
# Note on context managers used by fixtures
#
# Because these context managers modify global state, they should really
# ONLY be used persistently (i.e., around yield statements) in
# function-scoped fixtures, OR in autouse session- or module-scoped
# fixtures.
#
# If they're used in regular tests or in module-scoped fixtures that are
# then injected as function arguments, weird things can happen, because
# the original state won't be restored until *after* the fixture is
# destroyed.  This makes sense for an autouse fixture, where you know
# everything in the module/session is going to need the modified
# behavior, but modifying global state for one function in a way that
# won't be restored until after the module or session is done essentially
# leaves garbage behind for other tests.
#
# In general, we should module- or session-scope the *STATE* required for
# these global objects, but we shouldn't module- or session-scope their
# *USE*, or things can get really confusing.
#


#
# Test-specific fixtures
#
@pytest.fixture(scope="session")
def mock_packages_repo():
    yield from_path(os.path.join(os.path.dirname(__file__), "repos", "spack_repo", "builtin_mock"))


def _pkg_install_fn(pkg, spec, prefix):
    # sanity_check_prefix requires something in the install directory
    mkdirp(prefix.bin)
    path = Path(spec.package.install_log_path)
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.touch()


@pytest.fixture
def mock_pkg_install(monkeypatch):
    monkeypatch.setattr(spack.package_base.PackageBase, "install", _pkg_install_fn, raising=False)


@pytest.fixture(scope="function")
def mock_packages(mock_packages_repo, mock_pkg_install, request):
    """Use the 'builtin_mock' repository instead of 'builtin'"""
    ensure_configuration_fixture_run_before(request)
    with use_repositories(mock_packages_repo) as mock_repo:
        yield mock_repo


@pytest.fixture(scope="session")
def linux_os():
    """Returns a named tuple with attributes 'name' and 'version'
    representing the OS.
    """
    platform = host_platform()
    name, version = "debian", "6"
    if platform.name == "linux":
        current_os = platform.default_operating_system()
        name, version = current_os.name, current_os.version
    LinuxOS = collections.namedtuple("LinuxOS", ["name", "version"])
    return LinuxOS(name=name, version=version)


@pytest.fixture(scope="session")
def configuration_dir(tmp_path_factory: pytest.TempPathFactory, linux_os):
    """Copies mock configuration files in a temporary directory. Returns the
    directory path.
    """
    tmp_path = tmp_path_factory.mktemp("configurations")
    install_tree_root = tmp_path_factory.mktemp("opt")

    # <test_path>/data/config has mock config yaml files in it
    # copy these to the site config.
    test_config = Path(__file__).parent / "data" / "config"
    shutil.copytree(test_config, tmp_path / "site")

    # Create temporary 'defaults', 'site' and 'user' folders
    (tmp_path / "user").mkdir()

    # Fill out config.yaml, compilers.yaml and modules.yaml templates.
    locks = sys.platform != "win32"
    config = tmp_path / "site" / "config.yaml"
    config_template = test_config / "config.yaml"
    config.write_text(config_template.read_text().format(install_tree_root, locks))

    target = str(host_cpu().family)
    compilers = tmp_path / "site" / "packages.yaml"
    compilers_template = test_config / "packages.yaml"
    compilers.write_text(compilers_template.read_text().format(linux_os=linux_os, target=target))

    yield tmp_path


def _create_mock_configuration_scopes(configuration_dir):
    """Create the configuration scopes used in `config` and `mutable_config`."""
    return [
        (ConfigScopePriority.DEFAULTS, InternalConfigScope("_builtin", CONFIG_DEFAULTS)),
        (
            ConfigScopePriority.CONFIG_FILES,
            DirectoryConfigScope("site", str(configuration_dir / "site")),
        ),
        (
            ConfigScopePriority.CONFIG_FILES,
            DirectoryConfigScope("system", str(configuration_dir / "system")),
        ),
        (
            ConfigScopePriority.CONFIG_FILES,
            DirectoryConfigScope("user", str(configuration_dir / "user")),
        ),
        (ConfigScopePriority.COMMAND_LINE, InternalConfigScope("command_line")),
    ]


@pytest.fixture(scope="session")
def mock_configuration_scopes(configuration_dir):
    """Create a persistent Configuration object from the configuration_dir."""
    yield _create_mock_configuration_scopes(configuration_dir)


@pytest.fixture(scope="function")
def config(mock_configuration_scopes):
    """This fixture activates/deactivates the mock configuration."""
    with use_configuration(*mock_configuration_scopes) as config:
        yield config


@pytest.fixture(scope="function")
def mutable_config(tmp_path_factory: pytest.TempPathFactory, configuration_dir):
    """Like config, but tests can modify the configuration."""
    mutable_dir = tmp_path_factory.mktemp("mutable_config") / "tmp"
    shutil.copytree(configuration_dir, mutable_dir)

    scopes = _create_mock_configuration_scopes(mutable_dir)
    with use_configuration(*scopes) as cfg:
        yield cfg


@pytest.fixture(autouse=True)
def mock_wsdk_externals(monkeypatch):
    """Skip check for required external packages on Windows during testing."""
    monkeypatch.setattr(spack.bootstrap, "ensure_winsdk_external_or_raise", _return_none)


def _populate(mock_db):
    r"""Populate a mock database with packages.

    Here is what the mock DB looks like (explicit roots at top):

    o  mpileaks     o  mpileaks'    o  mpileaks''     o externaltest     o trivial-smoke-test
    |\              |\              |\                |
    | o  callpath   | o  callpath'  | o  callpath''   o externaltool
    |/|             |/|             |/|               |
    o |  mpich      o |  mpich2     o |  zmpi         o externalvirtual
      |               |             o |  fake
      |               |               |
      |               |______________/
      | .____________/
      |/
      o  dyninst
      |\
      | o  libdwarf
      |/
      o  libelf
    """

    def _install(spec):
        s = concretize_one(spec)
        PackageInstaller([s.package], fake=True, explicit=True).install()

    _install("mpileaks ^mpich")
    _install("mpileaks ^mpich2")
    _install("mpileaks ^zmpi")
    _install("externaltest ^externalvirtual")
    _install("trivial-smoke-test")


@pytest.fixture(scope="session")
def _store_dir_and_cache(tmp_path_factory: pytest.TempPathFactory):
    """Returns the directory where to build the mock database and
    where to cache it.
    """
    store = tmp_path_factory.mktemp("mock_store")
    cache = tmp_path_factory.mktemp("mock_store_cache")
    return store, cache


@pytest.fixture(scope="session")
def mock_store(
    tmp_path_factory: pytest.TempPathFactory,
    mock_packages_repo,
    mock_configuration_scopes,
    _store_dir_and_cache: Tuple[Path, Path],
    glibc_compatibility,
):
    """Creates a read-only mock database with some packages installed note
    that the ref count for dyninst here will be 3, as it's recycled
    across each install.

    This does not actually activate the store for use by Spack -- see the
    ``database`` fixture for that.

    """
    store_path, store_cache = _store_dir_and_cache
    _mock_wsdk_externals = spack.bootstrap.ensure_winsdk_external_or_raise

    # Make the DB filesystem read-only to ensure constructors don't modify anything in it.
    # We want Spack to be able to point to a DB on a read-only filesystem easily.
    _recursive_chmod(store_path, 0o555)

    # If the cache does not exist populate the store and create it
    if not os.path.exists(str(store_cache / ".spack-db")):
        with use_configuration(*mock_configuration_scopes):
            with use_store(str(store_path)) as store:
                with use_repositories(mock_packages_repo):
                    # make the DB filesystem writable only while we populate it
                    _recursive_chmod(store_path, 0o755)
                    try:
                        spack.bootstrap.ensure_winsdk_external_or_raise = _return_none
                        _populate(store.db)
                    finally:
                        spack.bootstrap.ensure_winsdk_external_or_raise = _mock_wsdk_externals
                    _recursive_chmod(store_path, 0o555)

        _recursive_chmod(store_cache, 0o755)
        copy_tree(str(store_path), str(store_cache))
        _recursive_chmod(store_cache, 0o555)

    yield store_path


@pytest.fixture(scope="function")
def database_mutable_config(mock_store, mock_packages, mutable_config, monkeypatch):
    """This activates the mock store, packages, AND config."""
    with use_store(str(mock_store)) as store:
        yield store.db
        store.db.last_seen_verifier = ""


@pytest.fixture(scope="function")
def mutable_database(database_mutable_config, _store_dir_and_cache: Tuple[Path, Path]):
    """Writeable version of the fixture, restored to its initial state
    after each test.
    """
    # Make the database writeable, as we are going to modify it
    store_path, store_cache = _store_dir_and_cache
    _recursive_chmod(store_path, 0o755)

    yield database_mutable_config

    # Restore the initial state by copying the content of the cache back into
    # the store and making the database read-only
    shutil.rmtree(store_path)
    copy_tree(str(store_cache), str(store_path))
    _recursive_chmod(store_path, 0o555)


def _return_none(*args):
    return None


@pytest.fixture(scope="session")
def concretized_specs_cache():
    """Cache for mock concrete specs"""
    return {}


@pytest.fixture
def default_mock_concretization(config, mock_packages, concretized_specs_cache):
    """Return the default mock concretization of a spec literal, obtained using the mock
    repository and the mock configuration.

    This fixture is unsafe to call in a test when either the default configuration or mock
    repository are not used or have been modified.
    """

    def _func(spec_str, tests=False):
        key = spec_str, tests
        if key not in concretized_specs_cache:
            concretized_specs_cache[key] = concretize_one(spec_str, tests=tests)
        return concretized_specs_cache[key].copy()

    return _func


def pytest_runtest_setup(item):
    # Skip test marked "not_on_windows" if they're run on Windows
    not_on_windows_marker = item.get_closest_marker(name="not_on_windows")
    if not_on_windows_marker and sys.platform == "win32":
        pytest.skip(*not_on_windows_marker.args)

    # Skip items marked "only windows" if they're run anywhere but Windows
    only_windows_marker = item.get_closest_marker(name="only_windows")
    if only_windows_marker and sys.platform != "win32":
        pytest.skip(*only_windows_marker.args)


def _recursive_chmod(path: Path, mode: int):
    """Recursively change permissions of a directory and all its contents."""
    path.chmod(mode)
    for root, dirs, files in os.walk(path):
        for file in files:
            os.chmod(os.path.join(root, file), mode)
        for dir in dirs:
            os.chmod(os.path.join(root, dir), mode)


@pytest.fixture(autouse=True, scope="session")
def _c_compiler_always_exists():
    fn = spack.solver.asp.c_compiler_runs
    spack.solver.asp.c_compiler_runs = _true
    mthd = spack.compilers.libraries.CompilerPropertyDetector.default_libc
    spack.compilers.libraries.CompilerPropertyDetector.default_libc = _libc_from_python
    yield
    spack.solver.asp.c_compiler_runs = fn
    spack.compilers.libraries.CompilerPropertyDetector.default_libc = mthd


def _libc_from_python(self):
    return spack.spec.Spec("glibc@=2.28", external_path="/some/path")


def _true(x):
    return True


@pytest.fixture(scope="session", autouse=True)
def glibc_compatibility():
    """Selects whether we use OS compatibility for binaries, or libc compatibility."""
    if spack.platforms.real_host().name != "linux":
        return

    spack.solver.core.using_libc_compatibility = lambda: True
    spack.solver.runtimes.using_libc_compatibility = spack.solver.core.using_libc_compatibility
    spack.solver.asp.using_libc_compatibility = spack.solver.core.using_libc_compatibility
