import os
import sys

# Noop job
# CI_OIDC_REQUIRED: 0 - disable OIDC setup
# GIT_STRATEGY: none - don't clone anything
# Allocate a small runner
# CI_JOB_SIZE: small
# KUBERNETES_CPU_REQUEST: 100m
# KUBERNETES_MEMORY_REQUEST: 5M
NOOP_JOB = """
noop:
  image: busybox@sha256:37f7b378a29ceb4c551b1b5582e27747b855bbfaa73fa11914fe0df028dc581f
  variables:
    CI_OIDC_REQUIRED: 0
    GIT_STRATEGY: none
    CI_JOB_SIZE: small
    KUBERNETES_CPU_REQUEST: 100m
    KUBERNETES_MEMORY_REQUEST: 5M
  before_script: []
  after_script: []
  script:
  - echo "noop job generated by noop_job.py"
  tags: [service_noop, spack]
  retry: 0
  allow_failure: true
workflow:
  rules:
  - when: always
"""

if __name__ == "__main__":
    os.makedirs(os.path.dirname(sys.argv[1]))
    with open(sys.argv[1], "w", encoding="utf-8") as fd:
        fd.write(NOOP_JOB)
