ci:
  pipeline-gen:
  - build-job:
      after_script::
      - Write-Output "Done"

      before_script::
      - - mkdir .ci/tmp/spack
        - cd .ci/tmp/spack
        - git init
        - git remote add origin https://github.com/${SPACK_CHECKOUT_REPO}.git
        - git fetch --depth 1 origin ${SPACK_CHECKOUT_VERSION}
        - git checkout FETCH_HEAD
        - cd ${CI_PROJECT_DIR}
      - fsutil 8dot3name set C:\ 0
      - . ${SPACK_CI_SPACK_ROOT}\share\spack\setup-env.ps1
      - If (Test-Path -path C:\\key\intermediate_ci_signing_key.gpg) { spack.ps1 gpg trust -y C:\\key\intermediate_ci_signing_key.gpg }
      - If (Test-Path -path C:\\key\spack_public_key.gpg) { spack.ps1 gpg trust -y C:\\key\spack_public_key.gpg }

      script::
      - spack.ps1 env activate --without-view ${SPACK_CONCRETE_ENV_DIR}
      - spack.ps1 config add "config:install_tree:projections:${SPACK_JOB_SPEC_PKG_NAME}/${SPACK_JOB_SPEC_DAG_HASH}:'morepadding/{hash}'"
      - mkdir ${SPACK_ARTIFACTS_ROOT}/user_data
      - spack.ps1 --backtrace ci rebuild | Tee-Object -FilePath "${env:SPACK_ARTIFACTS_ROOT}/user_data/pipeline_out.txt" 2>&1 | Tee-Object -FilePath "${env:SPACK_ARTIFACTS_ROOT}/user_data/pipeline_err.txt"
      image: {
        name: "ghcr.io/johnwparent/windows-server21h2:sha-1c12b61",
        entrypoint: [""]
      }
