name: prechecks

on:
  workflow_call:
    inputs:
      with_packages:
        required: true
        type: string

concurrency:
  group: prechecks-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true


jobs:
  # Validate that the code can be run on all the Python versions supported by Spack
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
      with:
        python-version: '3.13'
    - name: Install Python Packages
      run: |
        pip install -r .github/workflows/requirements/style/requirements.txt
    - name: vermin (Repositories)
      run: |
        vermin --backport importlib --backport argparse --violations --backport typing -t=3.6- -vvv repos tests

  # Run style checks on the files that have been changed
  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 2
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
      with:
        python-version: '3.13'
    - name: Install Python packages
      run: |
        pip install -r .github/workflows/requirements/style/requirements.txt
    - uses: ./.github/actions/checkout-spack
      with:
        # This path must match the path in pyprojects.toml
        path: spack-core
    - name: Run style tests
      run: .ci/style_check.sh HEAD^
    # todo: license check
    # todo: mypy

  audit:
    uses: ./.github/workflows/audit.yaml
    secrets: inherit
    with:
      python_version: '3.13'

  verify-checksums:
    # do not run if the commit message or PR description contains [skip-verify-checksums]
    if: >-
      ${{ inputs.with_packages == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        # Depth 2 is required for this check
        fetch-depth: 2
    - uses: ./.github/actions/checkout-spack
      with:
        fetch-depth: 1
    - name: Verify Added Checksums
      run: |
        . spack-core/share/spack/setup-env.sh
        spack ci verify-versions HEAD~1 HEAD

  canonicalization:
    name: package.py canonicalization
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/spack/all-pythons:2025-10-10

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
      - uses: ./.github/actions/checkout-spack

      - name: Test package.py canonicalization
        run: .github/workflows/bin/canonicalize.py
          --spack $PWD/spack-core
          --python python3.6 python3.7 python3.8 python3.9 python3.10 python3.11 python3.12 python3.13 python3.14
          --input-dir repos/spack_repo/builtin/packages/
          --output-dir canonicalized
