name: unit tests

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: unit_tests-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  # Run unit tests with different configurations on linux
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        on_develop:
        - ${{ github.ref == 'refs/heads/develop' }}
        include:
        - python-version: '3.7'
          os: ubuntu-22.04
          on_develop: ${{ github.ref == 'refs/heads/develop' }}
        exclude:
        - python-version: '3.8'
          os: ubuntu-latest
          on_develop: false
        - python-version: '3.9'
          os: ubuntu-latest
          on_develop: false
        - python-version: '3.10'
          os: ubuntu-latest
          on_develop: false
        - python-version: '3.11'
          os: ubuntu-latest
          on_develop: false

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install System packages
      run: |
          sudo apt-get -y update
          # Needed for unit tests
          sudo apt-get -y install \
              coreutils cvs gfortran graphviz gnupg2 mercurial ninja-build \
              cmake bison libbison-dev subversion
    - name: Install Python packages
      run: pip install --upgrade pytest clingo
    - uses: ./.github/actions/checkout-spack
    - name: Run unit tests
      run: PYTHONPATH="$PWD/spack-core/lib/spack" python3 -m pytest -v --exitfirst

  # Run unit tests on MacOS
  macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-15", "macos-15-intel"]
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python packages
      run: pip install --upgrade pytest clingo
    - name: Setup Homebrew packages
      run: brew install dash fish gcc gnupg
    - uses: ./.github/actions/checkout-spack
    - name: Run unit tests
      run: PYTHONPATH="$PWD/spack-core/lib/spack" python3 -m pytest -v --exitfirst

  # Run unit tests on Windows
  windows:
    defaults:
      run:
        shell:
          powershell Invoke-Expression -Command "./.ci/windows_test_setup.ps1"; {0}
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
      with:
        python-version: 3.9
    - name: Install Python packages
      run: python -m pip install --upgrade pywin32 pytest clingo
    #- name: Create local develop
    #  run: |
    #    ./.github/workflows/bin/setup_git.ps1
    - uses: ./.github/actions/checkout-spack
    - name: Run unit tests
      run: |
        $Env:PYTHONPATH = "$Env:SPACK_ROOT\lib\spack;$Env:PYTHONPATH"
        python3 -m pytest -v --exitfirst
        ./.ci/validate_last_exit.ps1
